### ISSUE TITLE
Windows Issue

### ISSUE THREAD

**Issue by s-beji** [jsuarezruiz/netmaui-chat-app-challenge#2]
The Template does not work on Windows but on Android it seems working fine

Error
Severity Code Description Project File Line Suppression State
Error DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): Fehler 0x80070003: The Package "39E66DD9-0F5F-4097-9B78-1521B46229A0_9zz4h110yvjzm" cannot be installed or updated because the welcome screen image [appiconfgSplashScreen.png] cannot be loaded. Verify that the package contains an image that can be used as the splash screen for the application and that the package manifest points to the correct location of the splash screen image in the package. TravelApp

**Comment by BadranYahyaoui** [comment]
the issue is related to missing Visual Asset files, so instead in the solution you can go to Platforms/Windows/**Package.appxmanifest** and in **Visual Assets** tab go and replace **Assets\appiconLargeTile.png** by  ` $placeholder$.png `

**Comment by s-beji** [comment]
i needed also to replace the splashscreen via your descirbed way
